name              'osl-mailstore'
maintainer        'Oregon State University'
maintainer_email  'chef@osuosl.org'
license           'All Rights Reserved'
description       'Installs/Configures osl-mailstore'
issues_url        'https://github.com/osuosl-cookbooks/osl-mailstore/issues'
source_url        'https://github.com/osuosl-cookbooks/osl-mailstore'
chef_version      '>= 16.0'
version           '0.1.0'

depends           'osl-resources'
depends           'osl-apache'
depends           'osl-mysql'
depends           'osl-repos'

supports          'centos_stream', '~> 8.0'
