name              'osl-mailstore'
maintainer        'Oregon State University'
maintainer_email  'chef@osuosl.org'
license           'All Rights Reserved'
description       'Installs/Configures osl-mailstore'
issues_url        'https://github.com/osuosl-cookbooks/osl-mailstore/issues'
source_url        'https://github.com/osuosl-cookbooks/osl-mailstore'
chef_version      '>= 16.0'
version           '0.1.0'

supports          'centos', '~> 7.0'
supports          'centos', '~> 8.0'
